// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vot/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetNextVoteRequest struct {
}

func (m *QueryGetNextVoteRequest) Reset()         { *m = QueryGetNextVoteRequest{} }
func (m *QueryGetNextVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextVoteRequest) ProtoMessage()    {}
func (*QueryGetNextVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{2}
}
func (m *QueryGetNextVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextVoteRequest.Merge(m, src)
}
func (m *QueryGetNextVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextVoteRequest proto.InternalMessageInfo

type QueryGetNextVoteResponse struct {
	NextVote NextVote `protobuf:"bytes,1,opt,name=NextVote,proto3" json:"NextVote"`
}

func (m *QueryGetNextVoteResponse) Reset()         { *m = QueryGetNextVoteResponse{} }
func (m *QueryGetNextVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNextVoteResponse) ProtoMessage()    {}
func (*QueryGetNextVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{3}
}
func (m *QueryGetNextVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNextVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNextVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNextVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNextVoteResponse.Merge(m, src)
}
func (m *QueryGetNextVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNextVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNextVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNextVoteResponse proto.InternalMessageInfo

func (m *QueryGetNextVoteResponse) GetNextVote() NextVote {
	if m != nil {
		return m.NextVote
	}
	return NextVote{}
}

type QueryGetStoredVoteRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetStoredVoteRequest) Reset()         { *m = QueryGetStoredVoteRequest{} }
func (m *QueryGetStoredVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredVoteRequest) ProtoMessage()    {}
func (*QueryGetStoredVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{4}
}
func (m *QueryGetStoredVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredVoteRequest.Merge(m, src)
}
func (m *QueryGetStoredVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredVoteRequest proto.InternalMessageInfo

func (m *QueryGetStoredVoteRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetStoredVoteResponse struct {
	StoredVote StoredVote `protobuf:"bytes,1,opt,name=storedVote,proto3" json:"storedVote"`
}

func (m *QueryGetStoredVoteResponse) Reset()         { *m = QueryGetStoredVoteResponse{} }
func (m *QueryGetStoredVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStoredVoteResponse) ProtoMessage()    {}
func (*QueryGetStoredVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{5}
}
func (m *QueryGetStoredVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStoredVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStoredVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStoredVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStoredVoteResponse.Merge(m, src)
}
func (m *QueryGetStoredVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStoredVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStoredVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStoredVoteResponse proto.InternalMessageInfo

func (m *QueryGetStoredVoteResponse) GetStoredVote() StoredVote {
	if m != nil {
		return m.StoredVote
	}
	return StoredVote{}
}

type QueryAllStoredVoteRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredVoteRequest) Reset()         { *m = QueryAllStoredVoteRequest{} }
func (m *QueryAllStoredVoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredVoteRequest) ProtoMessage()    {}
func (*QueryAllStoredVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{6}
}
func (m *QueryAllStoredVoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredVoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredVoteRequest.Merge(m, src)
}
func (m *QueryAllStoredVoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredVoteRequest proto.InternalMessageInfo

func (m *QueryAllStoredVoteRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStoredVoteResponse struct {
	StoredVote []StoredVote        `protobuf:"bytes,1,rep,name=storedVote,proto3" json:"storedVote"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStoredVoteResponse) Reset()         { *m = QueryAllStoredVoteResponse{} }
func (m *QueryAllStoredVoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStoredVoteResponse) ProtoMessage()    {}
func (*QueryAllStoredVoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c59cfc6b644ee8a, []int{7}
}
func (m *QueryAllStoredVoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStoredVoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStoredVoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStoredVoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStoredVoteResponse.Merge(m, src)
}
func (m *QueryAllStoredVoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStoredVoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStoredVoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStoredVoteResponse proto.InternalMessageInfo

func (m *QueryAllStoredVoteResponse) GetStoredVote() []StoredVote {
	if m != nil {
		return m.StoredVote
	}
	return nil
}

func (m *QueryAllStoredVoteResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "greenbahar.vot.vot.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "greenbahar.vot.vot.QueryParamsResponse")
	proto.RegisterType((*QueryGetNextVoteRequest)(nil), "greenbahar.vot.vot.QueryGetNextVoteRequest")
	proto.RegisterType((*QueryGetNextVoteResponse)(nil), "greenbahar.vot.vot.QueryGetNextVoteResponse")
	proto.RegisterType((*QueryGetStoredVoteRequest)(nil), "greenbahar.vot.vot.QueryGetStoredVoteRequest")
	proto.RegisterType((*QueryGetStoredVoteResponse)(nil), "greenbahar.vot.vot.QueryGetStoredVoteResponse")
	proto.RegisterType((*QueryAllStoredVoteRequest)(nil), "greenbahar.vot.vot.QueryAllStoredVoteRequest")
	proto.RegisterType((*QueryAllStoredVoteResponse)(nil), "greenbahar.vot.vot.QueryAllStoredVoteResponse")
}

func init() { proto.RegisterFile("vot/query.proto", fileDescriptor_2c59cfc6b644ee8a) }

var fileDescriptor_2c59cfc6b644ee8a = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6b, 0x13, 0x41,
	0x18, 0xc6, 0xb3, 0xb5, 0x0d, 0xfa, 0x8a, 0x28, 0xd3, 0x88, 0xed, 0x12, 0x37, 0x3a, 0xd0, 0xc6,
	0xbf, 0x33, 0xa4, 0x5e, 0x3c, 0x29, 0x2d, 0x62, 0x6f, 0x5a, 0x23, 0x78, 0xe8, 0x45, 0x66, 0xd3,
	0x61, 0x1b, 0x48, 0x76, 0xb6, 0x3b, 0x93, 0x90, 0x22, 0xbd, 0x78, 0xf6, 0x20, 0x78, 0xf0, 0xe2,
	0x37, 0xf0, 0x8b, 0xf4, 0x24, 0x05, 0x2f, 0x9e, 0x44, 0x12, 0x3f, 0x88, 0xec, 0xcc, 0x6c, 0x76,
	0xdb, 0xdd, 0x26, 0xc5, 0x43, 0x42, 0xf2, 0xce, 0xfb, 0xbc, 0xcf, 0xef, 0x65, 0x9f, 0x59, 0xb8,
	0x3e, 0x14, 0x8a, 0x1e, 0x0c, 0x78, 0x7c, 0x48, 0xa2, 0x58, 0x28, 0x81, 0x50, 0x10, 0x73, 0x1e,
	0xfa, 0x6c, 0x9f, 0xc5, 0x64, 0x28, 0x54, 0xf2, 0x71, 0x6b, 0x81, 0x08, 0x84, 0x3e, 0xa6, 0xc9,
	0x2f, 0xd3, 0xe9, 0xd6, 0x03, 0x21, 0x82, 0x1e, 0xa7, 0x2c, 0xea, 0x52, 0x16, 0x86, 0x42, 0x31,
	0xd5, 0x15, 0xa1, 0xb4, 0xa7, 0x0f, 0x3a, 0x42, 0xf6, 0x85, 0xa4, 0x3e, 0x93, 0xdc, 0x18, 0xd0,
	0x61, 0xcb, 0xe7, 0x8a, 0xb5, 0x68, 0xc4, 0x82, 0x6e, 0xa8, 0x9b, 0x6d, 0xef, 0x8d, 0x04, 0x22,
	0x62, 0x31, 0xeb, 0xa7, 0xea, 0xe5, 0xa4, 0x12, 0xf2, 0x91, 0x7a, 0x3f, 0x14, 0x8a, 0xdb, 0xe2,
	0xcd, 0xa4, 0x28, 0x95, 0x88, 0xf9, 0x5e, 0xae, 0x8c, 0x6b, 0x80, 0xde, 0x24, 0xf3, 0x77, 0xf4,
	0x80, 0x36, 0x3f, 0x18, 0x70, 0xa9, 0xf0, 0x6b, 0x58, 0x3e, 0x55, 0x95, 0x91, 0x08, 0x25, 0x47,
	0x4f, 0xa1, 0x6a, 0x8c, 0x56, 0x9c, 0x3b, 0xce, 0xbd, 0xab, 0x1b, 0x2e, 0x29, 0xee, 0x4b, 0x8c,
	0x66, 0x6b, 0xf1, 0xf8, 0x77, 0xa3, 0xd2, 0xb6, 0xfd, 0x78, 0x15, 0x6e, 0xe9, 0x81, 0xdb, 0x5c,
	0xbd, 0xe2, 0x23, 0xf5, 0x4e, 0x28, 0x9e, 0x7a, 0xed, 0xc2, 0x4a, 0xf1, 0xc8, 0x1a, 0x3e, 0x83,
	0xcb, 0x69, 0xcd, 0x5a, 0xd6, 0xcb, 0x2c, 0xd3, 0x1e, 0x6b, 0x3a, 0xd5, 0xe0, 0x16, 0xac, 0xa6,
	0xb3, 0xdf, 0xea, 0xd5, 0x73, 0xc6, 0xa8, 0x06, 0x4b, 0xdd, 0x70, 0x8f, 0x8f, 0xf4, 0xe4, 0x2b,
	0x6d, 0xf3, 0x07, 0xfb, 0xe0, 0x96, 0x49, 0x2c, 0xd0, 0x0b, 0x00, 0x39, 0xad, 0x5a, 0x24, 0xaf,
	0x0c, 0x29, 0xd3, 0x5a, 0xa8, 0x9c, 0x0e, 0x77, 0x2c, 0xd6, 0x66, 0xaf, 0x57, 0xc4, 0x7a, 0x09,
	0x90, 0x3d, 0x63, 0x6b, 0xb1, 0x4e, 0x4c, 0x20, 0x48, 0x12, 0x08, 0x62, 0x12, 0x67, 0x03, 0x41,
	0x76, 0x58, 0x90, 0x6a, 0xdb, 0x39, 0x25, 0xfe, 0xee, 0xd8, 0x4d, 0xce, 0xb8, 0x9c, 0xb3, 0xc9,
	0xa5, 0xff, 0xd9, 0x04, 0x6d, 0x9f, 0x82, 0x5d, 0xd0, 0xb0, 0xcd, 0xb9, 0xb0, 0x06, 0x21, 0x4f,
	0xbb, 0xf1, 0x63, 0x11, 0x96, 0x34, 0x2d, 0x3a, 0x82, 0xaa, 0x89, 0x10, 0x5a, 0x2f, 0xc3, 0x29,
	0xa6, 0xd5, 0x6d, 0xce, 0xed, 0x33, 0x86, 0x18, 0x7f, 0xfc, 0xf9, 0xf7, 0xcb, 0x42, 0x1d, 0xb9,
	0x34, 0x13, 0xd0, 0xe4, 0x5e, 0x64, 0x57, 0x08, 0x7d, 0x72, 0xb2, 0xcc, 0xa1, 0x87, 0xe7, 0x4e,
	0x2e, 0x06, 0xd9, 0x7d, 0x74, 0xb1, 0x66, 0xcb, 0xb2, 0xa6, 0x59, 0x1a, 0xe8, 0x76, 0x19, 0xcb,
	0xf4, 0xf2, 0xa2, 0x6f, 0x0e, 0x40, 0xf6, 0x04, 0xd0, 0xe3, 0x59, 0x1e, 0x85, 0x2c, 0xb9, 0xe4,
	0xa2, 0xed, 0x16, 0x8a, 0x6a, 0xa8, 0xfb, 0xa8, 0x59, 0x06, 0x95, 0x7b, 0x79, 0xd0, 0x0f, 0xfa,
	0xb2, 0x1c, 0xa1, 0xaf, 0x0e, 0x5c, 0xcb, 0xe6, 0x6c, 0xf6, 0x7a, 0x33, 0x08, 0xcb, 0xd2, 0x3e,
	0x83, 0xb0, 0x34, 0xb6, 0xb8, 0xa9, 0x09, 0xef, 0xa2, 0xc6, 0x1c, 0xc2, 0xad, 0xe7, 0xc7, 0x63,
	0xcf, 0x39, 0x19, 0x7b, 0xce, 0x9f, 0xb1, 0xe7, 0x7c, 0x9e, 0x78, 0x95, 0x93, 0x89, 0x57, 0xf9,
	0x35, 0xf1, 0x2a, 0xbb, 0x6b, 0x41, 0x57, 0xed, 0x0f, 0x7c, 0xd2, 0x11, 0xfd, 0xb3, 0x43, 0x46,
	0xfa, 0x5b, 0x1d, 0x46, 0x5c, 0xfa, 0x55, 0xfd, 0x82, 0x7c, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0x27, 0xc9, 0x84, 0xe5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a NextVote by index.
	NextVote(ctx context.Context, in *QueryGetNextVoteRequest, opts ...grpc.CallOption) (*QueryGetNextVoteResponse, error)
	// Queries a StoredVote by index.
	StoredVote(ctx context.Context, in *QueryGetStoredVoteRequest, opts ...grpc.CallOption) (*QueryGetStoredVoteResponse, error)
	// Queries a list of StoredVote items.
	StoredVoteAll(ctx context.Context, in *QueryAllStoredVoteRequest, opts ...grpc.CallOption) (*QueryAllStoredVoteResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/greenbahar.vot.vot.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NextVote(ctx context.Context, in *QueryGetNextVoteRequest, opts ...grpc.CallOption) (*QueryGetNextVoteResponse, error) {
	out := new(QueryGetNextVoteResponse)
	err := c.cc.Invoke(ctx, "/greenbahar.vot.vot.Query/NextVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredVote(ctx context.Context, in *QueryGetStoredVoteRequest, opts ...grpc.CallOption) (*QueryGetStoredVoteResponse, error) {
	out := new(QueryGetStoredVoteResponse)
	err := c.cc.Invoke(ctx, "/greenbahar.vot.vot.Query/StoredVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StoredVoteAll(ctx context.Context, in *QueryAllStoredVoteRequest, opts ...grpc.CallOption) (*QueryAllStoredVoteResponse, error) {
	out := new(QueryAllStoredVoteResponse)
	err := c.cc.Invoke(ctx, "/greenbahar.vot.vot.Query/StoredVoteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a NextVote by index.
	NextVote(context.Context, *QueryGetNextVoteRequest) (*QueryGetNextVoteResponse, error)
	// Queries a StoredVote by index.
	StoredVote(context.Context, *QueryGetStoredVoteRequest) (*QueryGetStoredVoteResponse, error)
	// Queries a list of StoredVote items.
	StoredVoteAll(context.Context, *QueryAllStoredVoteRequest) (*QueryAllStoredVoteResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) NextVote(ctx context.Context, req *QueryGetNextVoteRequest) (*QueryGetNextVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextVote not implemented")
}
func (*UnimplementedQueryServer) StoredVote(ctx context.Context, req *QueryGetStoredVoteRequest) (*QueryGetStoredVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredVote not implemented")
}
func (*UnimplementedQueryServer) StoredVoteAll(ctx context.Context, req *QueryAllStoredVoteRequest) (*QueryAllStoredVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoredVoteAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenbahar.vot.vot.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NextVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNextVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenbahar.vot.vot.Query/NextVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextVote(ctx, req.(*QueryGetNextVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStoredVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenbahar.vot.vot.Query/StoredVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredVote(ctx, req.(*QueryGetStoredVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StoredVoteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStoredVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StoredVoteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenbahar.vot.vot.Query/StoredVoteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StoredVoteAll(ctx, req.(*QueryAllStoredVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greenbahar.vot.vot.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NextVote",
			Handler:    _Query_NextVote_Handler,
		},
		{
			MethodName: "StoredVote",
			Handler:    _Query_StoredVote_Handler,
		},
		{
			MethodName: "StoredVoteAll",
			Handler:    _Query_StoredVoteAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vot/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetNextVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetNextVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNextVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNextVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NextVote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStoredVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStoredVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStoredVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.StoredVote.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredVoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredVoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredVoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStoredVoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStoredVoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStoredVoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.StoredVote) > 0 {
		for iNdEx := len(m.StoredVote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StoredVote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetNextVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetNextVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NextVote.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetStoredVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetStoredVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoredVote.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllStoredVoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStoredVoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StoredVote) > 0 {
		for _, e := range m.StoredVote {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNextVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNextVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNextVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextVote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStoredVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStoredVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStoredVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoredVote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredVoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredVoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredVoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStoredVoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStoredVoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStoredVoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoredVote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StoredVote = append(m.StoredVote, StoredVote{})
			if err := m.StoredVote[len(m.StoredVote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
